[platformio]
default_envs =
  color_detection_reference
  face_detection_reference

[env]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_build.flash_size = 8MB
board_build.arduino.memory_type = qio_opi
build_unflags = -std=gnu++11
build_flags =
  -std=gnu++17
  -Wall
  -Wextra
  -Werror
  -pedantic

[env:color_detection_reference]
build_flags =
  ${env.build_flags}
  -DESP32S3_CAM_PROFILE_COLOR=1

[env:face_detection_reference]
build_flags =
  ${env.build_flags}
  -DESP32S3_CAM_PROFILE_FACE=1
