schema_version: 1
calibration_id: FIELD-MID360-MANUAL
calibration_status: MANUAL
calibration_hash: 5db1fb261c588379300b27dfd236bdd2fb83a5795ef95ebe1c34cdfff991de6a
sensor_serials:
  camera_narrow: UNSET
  camera_wide: UNSET
  lidar: MWLDA24001H3J22
transforms:
  fcu_link:
    xyz_m:
    - 0.0
    - 0.0
    - 0.0
    rpy_rad:
    - 0.0
    - 0.0
    - 0.0
  lidar_link:
    xyz_m:
    - 0.0
    - 0.0
    - 0.0
    rpy_rad:
    - 0.0
    - 0.0
    - 0.0
  camera_narrow_optical_frame:
    xyz_m:
    - 0.0
    - 0.0
    - 0.0
    rpy_rad:
    - 0.0
    - 0.0
    - 0.0
  camera_wide_optical_frame:
    xyz_m:
    - 0.0
    - 0.0
    - 0.0
    rpy_rad:
    - 0.0
    - 0.0
    - 0.0
  rangefinder_link:
    xyz_m:
    - 0.0
    - 0.0
    - 0.0
    rpy_rad:
    - 0.0
    - 0.0
    - 0.0
